module.exports = {
  Divine: '✧',
  Chaos: '⦲',
  Mystic: '☾',
  Dark: '❍',
  Spirit: '⧂',
  Oblivion: '⨙',
  Corporeal: '⩀',
  Creature: '⧰',
  Verdure: '❖',
  Toxic: '⦵',
  Mundane: '⬙',
  Aqueous: '⏆',
  Cosmos: '✶',
  Inferno: '◊',
  Geological: '◍',
  Automoton: '⬡',
  Numerary: '☉',
  Alchemy: '⦓',
};
